### ISSUE TITLE
The Bot-Players are too good!

### ISSUE THREAD

**Issue by tevans78** [liberty-bikes/liberty-bikes#137]
When there are only one or two human players, chances are that one of the bots will usually win. This might be partly due to the lag introduced by using a mobile phone as a controller.

**Comment by aguibert** [comment]
We think the AI tuning is fine, one of the AIs is easier than the other.  They are definitely beatable, and it encourages people to stick around for a few games if it is a little challenging.

**Comment by tevans78** [comment]
OK your call but make sure that you have tried it using a mobile phone connected to a slowish network ... it is much harder than when using a laptop client with a good network.
