### ISSUE TITLE
Sometimes the player controlled bikes are started facing the wall

### ISSUE THREAD

**Issue by tevans78** [liberty-bikes/liberty-bikes#139]
The player doesn't get a chance to react and crashes straight away.

**Comment by aguibert** [comment]
On each map players always start facing away from a wall, but they can change directions before the game starts (but the bikes don't turn until the game starts).

**Comment by aguibert** [comment]
Re-opening this one so we can implement one of the following resolutions:
A) don't allow direction changes before game starts
B) allow direction changes before game starts, but show the players rotating before the game starts instead of deferring the rotation until the start of game

**Comment by olendvcook** [comment]
We went with option B in PR #184, and updated one of the maps that has the bottom right player start facing the wall.
