### ISSUE TITLE
Remove party code for conferences/events

### ISSUE THREAD

**Issue by mbroz2** [liberty-bikes/liberty-bikes#147]
When using the app at an event/conference, the same party code tends to not change. If there are machines setup to play locally (since using a phone would take longer to open a browser, navigate to the site, and hope the internet at the conference is fast enough), users should be able to quickly join the hosted game without needing to type in the code.  
Two possible approaches are:
1) Users should be able to remain on the game page and just change the username
2) Eliminate the need for users to type in the party code on the current login page (either by removing the code entirely, or populating the field with the last-used code.

W/e the solution, the goal is to streamline users coming and going when using dedicated machines at events; for the end user, they only care that they can see their name to help identify their bike as well as for the leadboard.

**Comment by aguibert** [comment]
We have gone with option (2) and implemented a single-party mode, where users can use the "Play Now" option to join in on the only party for the deployment.

Resolved by PR #144
